services:
  - type: web
    name: tft-review-api
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt
      cd backend
      python -c "import time; time.sleep(10)"  # Wait longer for DB to be ready

      # Step 1: Initialize the database with all tables
      echo "Step 1: Initializing database..."
      python db_init.py

      # Step 2: Run manual migration to fix any schema issues
      echo "Step 2: Running manual migration..."
      python run_manual_migration.py

      # Step 3: Make sure alembic_version is set to the latest migration
      echo "Step 3: Fixing migration history..."
      python fix_migrations.py

      # Step 4: Run Alembic migrations for any new changes
      echo "Step 4: Running alembic migrations..."
      export PYTHONWARNINGS="ignore:.*"
      alembic upgrade head || echo "Ignoring potential migration errors and continuing"
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tft-review-db
          property: connectionString
      - key: POSTGRES_URL
        fromDatabase:
          name: tft-review-db
          property: connectionString
      - key: AUTH0_DOMAIN
        sync: false
      - key: AUTH0_AUDIENCE
        sync: false
      - key: CORS_ORIGINS
        value: https://bettertft.com,https://www.bettertft.com
      - key: FRONTEND_URL
        value: https://bettertft.com
      - key: RIOT_CLIENT_ID
        sync: false
      - key: RIOT_CLIENT_SECRET
        sync: false
      - key: RIOT_REDIRECT_URI
        value: https://bettertft.com/auth/riot/callback
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: WASABI_ACCESS_KEY_ID
        sync: false
      - key: WASABI_SECRET_ACCESS_KEY
        sync: false
      - key: WASABI_BUCKET_NAME
        sync: false
      - key: WASABI_REGION
        value: us-central-1
      - key: WASABI_ENDPOINT_URL
        value: https://s3.us-central-1.wasabisys.com
    healthCheckPath: /api/v1/health

  - type: web
    name: tft-review-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://tft-review-api.onrender.com
      - key: REACT_APP_AUTH0_DOMAIN
        sync: false
      - key: REACT_APP_AUTH0_CLIENT_ID
        sync: false
      - key: REACT_APP_AUTH0_AUDIENCE
        sync: false
    domains:
      - bettertft.com
      - www.bettertft.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: tft-review-db
    databaseName: tft_review
    user: tft_review_user
