"""add_parent_id_and_timestamp_to_comment

Revision ID: 17adc040a316
Revises: e2b57120079f
Create Date: 2025-05-12 09:26:25.569566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17adc040a316'
down_revision: Union[str, None] = 'e2b57120079f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('video_timestamp', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'comment', 'comment', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'video_timestamp')
    op.drop_column('comment', 'parent_id')
    # ### end Alembic commands ###
