"""Add Riot account fields to User model

Revision ID: 22da4a8bc75b
Revises: 982aa0a44b7e
Create Date: 2023-05-19 12:34:56.789012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22da4a8bc75b'
down_revision = '982aa0a44b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - modified for safety ###
    op.add_column('user', sa.Column('riot_account_name', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('riot_account_tag', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('riot_region', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('riot_access_token', sa.String(length=2000), nullable=True))
    op.add_column('user', sa.Column('riot_refresh_token', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - modified for safety ###
    op.drop_column('user', 'riot_refresh_token')
    op.drop_column('user', 'riot_access_token')
    op.drop_column('user', 'riot_region')
    op.drop_column('user', 'riot_account_tag')
    op.drop_column('user', 'riot_account_name')
    # ### end Alembic commands ###
