"""add_description_and_event_type_to_event

Revision ID: 982aa0a44b7e
Revises: 717c9c1c6795
Create Date: 2025-05-15 11:26:43.356012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '982aa0a44b7e'
down_revision: Union[str, None] = '717c9c1c6795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('event', sa.Column('event_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'event_type')
    op.drop_column('event', 'description')
    # ### end Alembic commands ###
