"""add_event_id_to_comments

Revision ID: adc297d50e95
Revises: 971291895341
Create Date: 2025-05-14 14:26:27.023150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc297d50e95'
down_revision: Union[str, None] = '971291895341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'event', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'event_id')
    # ### end Alembic commands ###
